"use strict";

const LEGACY_TO_CURRENT = {
    "callback-return": "n/callback-return",
    "id-blacklist": "id-denylist",
    "lines-around-directive": "@stylistic/padding-line-between-statements",
    "newline-after-var": "@stylistic/padding-line-between-statements",
    "newline-before-return": "@stylistic/padding-line-between-statements",
    "no-catch-shadow": "no-shadow",
    "no-mixed-requires": "n/no-mixed-requires",
    "no-native-reassign": "no-global-assign",
    "no-negated-in-lhs": "no-unsafe-negation",
    "no-new-require": "n/no-new-require",
    "no-path-concat": "n/no-path-concat",
    "no-process-env": "n/no-process-env",
    "no-process-exit": "n/no-process-exit",
    "no-restricted-modules": "n/no-restricted-require",
    "no-sync": "n/no-sync",
    "no-spaced-func": "@stylistic/function-call-spacing",
    "global-require": "n/global-require",
    "handle-callback-err": "n/handle-callback-err",
    "func-call-spacing": "@stylistic/function-call-spacing",
    "function-call-spacing": "@stylistic/function-call-spacing",
    "require-jsdoc": "jsdoc/require-jsdoc",
    "valid-jsdoc": "jsdoc/check-tag-names",
    "array-bracket-spacing": "@stylistic/array-bracket-spacing",
    "arrow-parens": "@stylistic/arrow-parens",
    "arrow-spacing": "@stylistic/arrow-spacing",
    "block-spacing": "@stylistic/block-spacing",
    "brace-style": "@stylistic/brace-style",
    "comma-dangle": "@stylistic/comma-dangle",
    "comma-spacing": "@stylistic/comma-spacing",
    "comma-style": "@stylistic/comma-style",
    "computed-property-spacing": "@stylistic/computed-property-spacing",
    "dot-location": "@stylistic/dot-location",
    "eol-last": "@stylistic/eol-last",
    "generator-star-spacing": "@stylistic/generator-star-spacing",
    "indent": "@stylistic/indent",
    "jsx-quotes": "@stylistic/jsx-quotes",
    "key-spacing": "@stylistic/key-spacing",
    "keyword-spacing": "@stylistic/keyword-spacing",
    "linebreak-style": "@stylistic/linebreak-style",
    "max-statements-per-line": "@stylistic/max-statements-per-line",
    "new-parens": "@stylistic/new-parens",
    "no-confusing-arrow": "@stylistic/no-confusing-arrow",
    "no-extra-parens": "@stylistic/no-extra-parens",
    "no-floating-decimal": "@stylistic/no-floating-decimal",
    "no-mixed-operators": "@stylistic/no-mixed-operators",
    "no-multi-spaces": "@stylistic/no-multi-spaces",
    "no-multiple-empty-lines": "@stylistic/no-multiple-empty-lines",
    "no-tabs": "@stylistic/no-tabs",
    "no-trailing-spaces": "@stylistic/no-trailing-spaces",
    "no-whitespace-before-property": "@stylistic/no-whitespace-before-property",
    "object-curly-newline": "@stylistic/object-curly-newline",
    "object-curly-spacing": "@stylistic/object-curly-spacing",
    "object-property-newline": "@stylistic/object-property-newline",
    "one-var-declaration-per-line": "@stylistic/one-var-declaration-per-line",
    "operator-linebreak": "@stylistic/operator-linebreak",
    "padded-blocks": "@stylistic/padded-blocks",
    "padding-line-between-statements": "@stylistic/padding-line-between-statements",
    "quote-props": "@stylistic/quote-props",
    "quotes": "@stylistic/quotes",
    "rest-spread-spacing": "@stylistic/rest-spread-spacing",
    "semi": "@stylistic/semi",
    "semi-spacing": "@stylistic/semi-spacing",
    "space-before-blocks": "@stylistic/space-before-blocks",
    "space-before-function-paren": "@stylistic/space-before-function-paren",
    "space-in-parens": "@stylistic/space-in-parens",
    "space-infix-ops": "@stylistic/space-infix-ops",
    "space-unary-ops": "@stylistic/space-unary-ops",
    "spaced-comment": "@stylistic/spaced-comment",
    "template-curly-spacing": "@stylistic/template-curly-spacing",
    "template-tag-spacing": "@stylistic/template-tag-spacing",
    "wrap-iife": "@stylistic/wrap-iife",
    "yield-star-spacing": "@stylistic/yield-star-spacing",
};

/**
 * Rules that were explicitly "off" in previous-index.js and have been
 * intentionally omitted from the new flat config entirely (not even set to
 * "off"). Treating a missing entry the same as "off" is correct here — the
 * behaviour is identical and no regression has occurred.
 */
const INTENTIONALLY_OMITTED = new Set([
    "lines-around-comment",
    "multiline-ternary",
    "newline-per-chained-call",
]);

module.exports = { LEGACY_TO_CURRENT, INTENTIONALLY_OMITTED };
